### ISSUE TITLE
Crash when initialize

### ISSUE THREAD

**Issue by lostopkk** [frikinjay/mob-stacker#11] opened 2024-12-17 14:14 UTC
Version: 1.20.4

Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Callback method mobstacker$onDieAllScore(Lnet/minecraft/world/damagesource/DamageSource;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V in mobstacker.mixins.json:LivingEntityMixin from mod mobstacker failed injection check, (0/1) succeeded. Scanned 0 target(s). No refMap loaded.

**Comment by LydiaLambda** [comment] 2024-12-18 18:46
### Same error happens to me with Minecraft 1.21.4

> [12:34:18] [main/ERROR]: Failed to start the minecraft server
java.lang.RuntimeException: Mixin transformation of net.minecraft.class_1309 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427) ~[fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.16.9.jar:?]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:528) ~[?:?]
	at java.base/java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1026) ~[?:?]
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:160) ~[fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:355) ~[fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.16.9.jar:?]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:528) ~[?:?]
	at knot/net.minecraft.class_2966.method_12851(class_2966.java:55) ~[server-intermediary.jar:?]
	at knot/net.minecraft.server.Main.main(Main.java:110) [server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) [fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.16.9.jar:?]
	at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) [fabric-server.jar:1.0.1]
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.16.9.jar:?]
	... 19 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Callback method mobstacker$onDieAllScore(Lnet/minecraft/class_1282;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V in mobstacker.mixins.json:LivingEntityMixin from mod mobstacker failed injection check, (0/1) succeeded. Scanned 0 target(s). Using refmap MobStacker-1.21.3-common-common-refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:531) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1490) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:752) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:330) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:246) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:437) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:418) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.16.9.jar:?]
	... 19 more


### Mod list:

>[12:34:10] [main/INFO]: Loading 115 mods:
	- almanac 1.4.4
	- appleskin 3.0.6+mc1.21.3
	- async 0.1.5+alpha.5-1.21.4
	   |-- com_electronwill_night-config_core 3.8.1
	   |-- com_electronwill_night-config_toml 3.8.1
	   \-- mixinsquared 0.2.0-beta.6
	- balm-fabric 21.4.1
	   \-- kuma_api 21.4.3
	- bookshelfinspector 1.9+1.21.4
	   \-- org_yaml_snakeyaml 2.2
	- c2me 0.3.1+beta.2.0+1.21.4
	   |-- c2me-base 0.3.1+beta.2.0+1.21.4
	   |-- c2me-client-uncapvd 0.3.1+beta.2.0+1.21.4
	   |-- c2me-fixes-chunkio-threading-issues 0.3.1+beta.2.0+1.21.4
	   |-- c2me-fixes-general-threading-issues 0.3.1+beta.2.0+1.21.4
	   |-- c2me-fixes-worldgen-threading-issues 0.3.1+beta.2.0+1.21.4
	   |-- c2me-fixes-worldgen-vanilla-bugs 0.3.1+beta.2.0+1.21.4
	   |-- c2me-notickvd 0.3.1+beta.2.0+1.21.4
	   |-- c2me-opts-allocs 0.3.1+beta.2.0+1.21.4
	   |-- c2me-opts-chunkio 0.3.1+beta.2.0+1.21.4
	   |-- c2me-opts-dfc 0.3.1+beta.2.0+1.21.4
	   |-- c2me-opts-math 0.3.1+beta.2.0+1.21.4
	   |-- c2me-opts-natives-math 0.3.1+beta.2.0+1.21.4
	   |-- c2me-opts-scheduling 0.3.1+beta.2.0+1.21.4
	   |-- c2me-opts-worldgen-general 0.3.1+beta.2.0+1.21.4
	   |-- c2me-opts-worldgen-vanilla 0.3.1+beta.2.0+1.21.4
	   |-- c2me-rewrites-chunk-serializer 0.3.1+beta.2.0+1.21.4
	   |-- c2me-rewrites-chunk-system 0.3.1+beta.2.0+1.21.4
	   |-- c2me-rewrites-chunkio 0.3.1+beta.2.0+1.21.4
	   |-- c2me-server-utils 0.3.1+beta.2.0+1.21.4
	   |-- c2me-threading-lighting 0.3.1+beta.2.0+1.21.4
	   |-- com_ibm_async_asyncutil 0.1.0
	   |-- io_reactivex_rxjava3_rxjava 3.1.8
	   |-- net_objecthunter_exp4j 0.4.8
	   |-- org_jctools_jctools-core 4.0.5
	   \-- org_reactivestreams_reactive-streams 1.0.4
	- cloth-config 17.0.144
	   \-- cloth-basic-math 0.6.1
	- collective 7.89
	- controlify 2.0.0-beta.21+1.21.4-fabric
	   |-- dev_isxander_libsdl4j 3.preview-3.1.3-46
	   |-- dev_isxander_steamdeck4j 1.1.6
	   |-- mixinextras 0.5.0-beta.4
	   |-- org_hid4java_hid4java 0.8.0
	   |-- org_quiltmc_parsers_gson 0.3.0
	   \-- org_quiltmc_parsers_json 0.3.0
	- debugify 1.21.4+1.0
	- doubledoors 6.0
	- fabric-api 0.112.0+1.21.4
	   |-- fabric-api-base 0.4.53+453d4f9104
	   |-- fabric-api-lookup-api-v1 1.6.85+b1caf1e904
	   |-- fabric-biome-api-v1 15.0.5+b1caf1e904
	   |-- fabric-block-api-v1 1.0.31+7feeb73304
	   |-- fabric-block-view-api-v2 1.0.19+7feeb73304
	   |-- fabric-blockrenderlayer-v1 2.0.7+7feeb73304
	   |-- fabric-client-tags-api-v1 1.1.28+20ea1e2304
	   |-- fabric-command-api-v1 1.2.61+f71b366f04
	   |-- fabric-command-api-v2 2.2.40+e496eb1504
	   |-- fabric-commands-v0 0.2.78+df3654b304
	   |-- fabric-content-registries-v0 9.1.13+7feeb73304
	   |-- fabric-convention-tags-v1 2.1.7+7f945d5b04
	   |-- fabric-convention-tags-v2 2.9.7+b1caf1e904
	   |-- fabric-crash-report-info-v1 0.3.6+7feeb73304
	   |-- fabric-data-attachment-api-v1 1.4.4+9aea556b04
	   |-- fabric-data-generation-api-v1 22.2.0+20ea1e2304
	   |-- fabric-dimensions-v1 4.0.10+7feeb73304
	   |-- fabric-entity-events-v1 2.0.11+60fccc7604
	   |-- fabric-events-interaction-v0 4.0.1+a4eebcf004
	   |-- fabric-game-rule-api-v1 1.0.62+7feeb73304
	   |-- fabric-item-api-v1 11.1.13+203e6b2304
	   |-- fabric-item-group-api-v1 4.1.22+7feeb73304
	   |-- fabric-key-binding-api-v1 1.0.56+7feeb73304
	   |-- fabric-keybindings-v0 0.2.54+df3654b304
	   |-- fabric-lifecycle-events-v1 2.5.3+bf2a60eb04
	   |-- fabric-loot-api-v2 3.0.32+3f89f5a504
	   |-- fabric-loot-api-v3 1.0.20+203e6b2304
	   |-- fabric-message-api-v1 6.0.24+7feeb73304
	   |-- fabric-model-loading-api-v1 4.1.0+7b6b225304
	   |-- fabric-networking-api-v1 4.3.8+cc0fa2fe04
	   |-- fabric-object-builder-api-v1 18.0.6+e604fe7f04
	   |-- fabric-particles-v1 4.0.13+7feeb73304
	   |-- fabric-recipe-api-v1 8.0.4+b1caf1e904
	   |-- fabric-registry-sync-v0 6.1.0+9ba00ebb04
	   |-- fabric-renderer-api-v1 5.0.1+84404cdd04
	   |-- fabric-renderer-indigo 2.0.1+84404cdd04
	   |-- fabric-rendering-data-attachment-v1 0.3.57+73761d2e04
	   |-- fabric-rendering-fluids-v1 3.1.18+7feeb73304
	   |-- fabric-rendering-v1 10.1.1+b874120c04
	   |-- fabric-resource-conditions-api-v1 5.0.13+203e6b2304
	   |-- fabric-resource-loader-v0 3.0.11+b1caf1e904
	   |-- fabric-screen-api-v1 2.0.37+7feeb73304
	   |-- fabric-screen-handler-api-v1 1.3.107+7feeb73304
	   |-- fabric-sound-api-v1 1.0.32+7feeb73304
	   |-- fabric-tag-api-v1 1.0.1+20ea1e2304
	   |-- fabric-transfer-api-v1 5.4.7+b1caf1e904
	   \-- fabric-transitive-access-wideners-v1 6.3.2+56e78b9b04
	- fabricloader 0.16.9
	- inventoryessentials 21.4.1
	- java 23
	- kiss 0.5.0
	   \-- midnightlib 1.6.6
	- krypton 0.2.8
	   \-- com_velocitypowered_velocity-native 3.3.0-SNAPSHOT
	- letmedespawn 1.4.4
	- lithium 0.14.3+mc1.21.4
	- minecraft 1.21.4
	- mixintrace 1.1.1+1.17
	- mobstacker 1.0.12
	- noisium 2.5.0+mc1.21.4
	- notenoughanimations 1.8.2
	- packetfixer 1.5.0
	- scalablelux 0.1.1+fabric.452731d
	- skinlayers3d 1.7.4
	- spark 1.10.121
	   \-- fabric-permissions-api-v0 0.3.3
	- villagernames 8.1
	- xaerominimap 24.6.2
	- xaeroworldmap 1.39.1
	- yet_another_config_lib_v3 3.6.2+1.21.4-fabric
	   |-- com_twelvemonkeys_common_common-image 3.12.0
	   |-- com_twelvemonkeys_common_common-io 3.12.0
	   |-- com_twelvemonkeys_common_common-lang 3.12.0
	   |-- com_twelvemonkeys_imageio_imageio-core 3.12.0
	   |-- com_twelvemonkeys_imageio_imageio-metadata 3.12.0
	   \-- com_twelvemonkeys_imageio_imageio-webp 3.12.0
	- yosbr 0.1.2

NOT caused by C2ME, removal still shows same behaviour.

**Comment by frikinjay** [comment] 2024-12-29 19:37
Fixed in 1.0.13

**Closed as completed by frikinjay** 2024-12-29 19:37 UTC
